updated

diff --git a/robot/frontend b/robot/frontend
--- a/robot/frontend
+++ b/robot/frontend
@@ -9,6 +9,31 @@ exit 1
 
 fi
 
-yum install nginx -y    >> /tmp/frontend.log
-systemctl enable nginx  >> /tmp/frontend.log
-systemctl start nginx   >> /tmp/frontend.log
+echo -n "Installing NGINX: "
+yum install nginx -y    &>> /tmp/frontend.log
+if [ $? -eq 0 ]; then
+  echo -e "\e[32m success \e[0m"
+else
+  echo -e "\e[31m failure \e[0m"
+fi
+
+echo -n "Starting NGINX: "
+systemctl enable nginx  &>> /tmp/frontend.log
+systemctl start nginx   &>> /tmp/frontend.log
+if [ $? -eq 0 ]; then
+  echo -e "\e[32m success \e[0m"
+else
+  echo -e "\e[31m failure \e[0m"
+fi
+
+
+# curl -s -L -o /tmp/frontend.zip "https://github.com/stans-robot-project/frontend/archive/main.zip"
+
+# cd /usr/share/nginx/html
+# rm -rf *
+# unzip /tmp/frontend.zip
+# mv frontend-main/* .
+# mv static/* .
+# rm -rf frontend-main README.md
+# mv localhost.conf /etc/nginx/default.d/roboshop.conf
+
